name: Android build

on: pushgit update-index --chmod=+x gradlew
  git add .
  git commit -m "Changing permission of gradlew"
  git push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run test
        run: ./gradlew test

      - name: Build Proejct
        run: ./gradlew assemble
